### ISSUE TITLE
Incompatibility with Guard Villagers

### ISSUE THREAD

**Issue by mrsterner** [ExDrill/Guarding#1]
Hello, at 
https://github.com/ExDrill/Guarding/blob/c9707ae40c98669581587c5c25f4db676aec0186/src/main/java/com/exdrill/guarding/Guarding.java#L85
you assume the defender is a player and cast to (PlayerEntity), which isnt the case with Guard Villagers installed and will crash, so i suggest you wrap it in a if(defender instanceof PlayerEntity player){
    [...]
}
instead of an unsafe cast

**Comment by ExDrill** [comment]
Thanks for reporting this, I'll be rolling out a fix soon!
