### ISSUE TITLE
Crashing on newer builds of Fabric

### ISSUE THREAD

**Issue by Sunconure11** [ExDrill/Guarding#2]
https://pastebin.com/0S3c0zXH

**Comment by Sunconure11** [comment]
@ExDrill

**Comment by Sunconure11** [comment]
https://github.com/LordDeatHunter/HarvestScythes/issues/35

https://github.com/Draylar/post-materia/issues/4

Possibly connected

**Comment by Tenuuu** [comment]
Having similar issue. Crash on launch. 

https://gist.github.com/Tenuuu/37335c8a56f2a54cbd0a4e0ea7139704

**Comment by Sunconure11** [comment]
Latest build of the mod did not solve this issue.

@ExDrill

**Comment by ExDrill** [comment]
This is not something I can't fix unfortunately, this is a problem with the library itself, and sadly the creator of the library isn't active, I'll see what I could do as the library as a lot of major issues at the moment.

**Comment by Sunconure11** [comment]
The dev has a discord. Maybe contact him there? Crimson#6452
